name: pantheon
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.4307158528827131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#352b24'
    - '#d3c9b8'
    - '#797066'
    - '#beb4a5'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
